apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ROOT
              value: "dc=example,dc=org"
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            # - name: LDAP_USERS
            #   valueFrom:
            #     secretKeyRef:
            #       key: users
            #       name: openldap
            # - name: LDAP_PASSWORDS
            #   valueFrom:
            #     secretKeyRef:
            #       key: passwords
            #       name: openldap
            - name: LDAP_CUSTOM_LDIF_DIR
              value: "/ldifs"
          ports:
            - name: tcp-ldap
              containerPort: 389
          volumeMounts:
          - name: ldap
            mountPath: /ldifs
      volumes:
      - name: ldap
        configMap:
          name: ldap